name: Bukkit-Api
version: '1.0.0'
main: minecraft.sightworld.bukkitapi.SightWorld
api-version: 1.16
author: Dwyur
load: STARTUP
depend:
  - ProtocolLib
commands:
  bukkit-api:
    aliases:
      - bapi